spring:
  profiles:
    active: test
  application:
    name: pilot
server:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
    context-path: /api/
  port: 8900


logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.logonedigital.pilot: INFO